
enum Languages {
  english("English", "en"),
  french("French", "fr"),
  arabic("Arabic", "ar"),
  czech("Czech", "cs"),
  german("German", "de"),
  spanish("Spanish", "es"),
  estonian("Estonian", "et"),
  finnish("Finnish", "fi"),
  gujarati("Gujarati", "gu"),
  hindi("Hindi", "hi"),
  italian("Italian", "it"),
  japanese("Japanese", "ja"),
  kazakh("Kazakh", "kk"),
  korean("Korean", "ko"),
  lithuanian("Lithuanian", "lt"),
  latvian("Latvian", "lv"),
  burmese("Burmese", "my"),
  nepali("Nepali", "ne"),
  dutch("Dutch", "nl"),
  romanian("Romanian", "ro"),
  russian("Russian", "ru"),
  sinhala("Sinhala", "si"),
  turkish("Turkish", "tr"),
  vietnamese("Vietnamese", "vi"),
  chinese("Chinese", "zh"),
  afrikaans("Afrikaans", "af"),
  azerbaijani("Azerbaijani", "az"),
  bengali("Bengali", "bn"),
  persian("Persian", "fa"),
  hebrew("Hebrew", "he"),
  croatian("Croatian", "hr"),
  indonesian("Indonesian", "id"),
  georgian("Georgian", "ka"),
  khmer("Khmer", "km"),
  macedonian("Macedonian", "mk"),
  malayalam("Malayalam", "ml"),
  mongolian("Mongolian", "mn"),
  marathi("Marathi", "mr"),
  polish("Polish", "pl"),
  pashto("Pashto", "ps"),
  portuguese("Portuguese", "pt"),
  swedish("Swedish", "sv"),
  swahili("Swahili", "sw"),
  tamil("Tamil", "ta"),
  telugu("Telugu", "te"),
  thai("Thai", "th"),
  tagalog("Tagalog", "tl"),
  ukrainian("Ukrainian", "uk"),
  urdu("Urdu", "ur"),
  xhosa("Xhosa", "xh"),
  galician("Galician", "gl"),
  slovene("Slovene", "sl");

  const Languages(this.label, this.val);
  final String label;
  final String val;

}